title: O jardim digital do Arthur
description: >-
  Algumas coisas estranhas acontecem por aqui...

url: https://arthr.dev
lang: pt-BR

permalink: /:year/:month/:day/:title.html

author:
  name: Arthur Freitas
  url: https://arthr.me
  picture: "https://gravatar.com/avatar/63d8285c2a55e1d4fefe7747e2c17ead9d3654dc39c4791adf088484105e5000?size=512"

collections:
  links:
    directory: _reading-list
    output: true
    permalink: /:collection/:title.html

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-json-feed

feed:
  collections:
    - links
